services:
  postgis-auth:
    image: postgres:latest
    container_name: auth-postgresql
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5433:5432"
    # expose:
    #   - "5432"
    volumes:
      - auth_service:/var/lib/postgresql/data
    restart: "no"
    networks:
      - default

volumes:
  auth_service:

networks:
  default: